name: Windows Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: ${{ matrix.arch }}
    - name: Install dependencies and pyinstall
      run: |
        python -m pip install pip==22.2.2 setuptools==65.3.0
        pip install -r requirements.txt
        pip install PyInstaller==5.3
    - name: Build binary
      run: |
        pyinstaller --onefile -n nanovna-saver.exe nanovna-saver.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NanoVNASaver.${{ matrix.arch }}
        path: dist/nanovna-saver.exe
